### ISSUE TITLE
**socket.error: [Errno 54] Connection reset by peer**

### ISSUE THREAD

**Issue by birdpillow** [aancw/Belati#23]
Hi,

I have problem reset by peer when checkin SVN target. Installation normal, and i tried -d rndc.or.id its working fine. But for several target, i get error **socket.error: [Errno 54] Connection reset by peer**. Any suggestion ? Thanks.

### Host System

- OS : MacOS HighSierra
- Python version (`python --version`) : 2.7.10
- Pip version (`pip --version`) : pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)
- Output of `pip freeze` : [Upload the output to GitHub gists and provide link]
altgraph==0.10.2
appnope==0.1.0
backports.shutil-get-terminal-size==1.0.0
bdist-mpkg==0.5.0
BeautifulSoup==3.2.1
beautifulsoup4==4.6.0
bonjour-py==0.3
certifi==2017.11.5
chardet==3.0.4
colorama==0.3.9
decorator==4.1.2
Django==1.8.2
dnsknife==0.11
dnspython==1.15.0
enum34==1.1.6
fake-useragent==0.1.8
future==0.16.0
futures==3.1.1
idna==2.6
ipython==5.5.0
ipython-genutils==0.2.0
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
pathlib2==2.3.0
pexpect==4.3.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
ptyprocess==0.5.2
py2app==0.7.3
pycrypto==2.6.1
pyexifinfo==0.4.0
Pygments==2.2.0
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
python-geoip==1.2
python-geoip-geolite2==2015.303
python-Wappalyzer==0.2.2
python-whois==0.6.5
pytz==2013.7
regex==2017.11.9
requests==2.18.4
requests-file==1.4.2
scandir==1.6
scipy==0.13.0b1
simplegeneric==0.8.1
six==1.11.0
termcolor==1.1.0
texttable==1.1.1
tldextract==2.2.0
tqdm==4.19.4
traitlets==4.3.2
urllib3==1.22
validators==0.12.0
virtualenv==15.1.0
wcwidth==0.1.7
xattr==0.6.4
zope.interface==4.1.1

### Error Description

Traceback (most recent call last):
  File "Belati.py", line 430, in <module>
    BelatiApp = Belati()
  File "Belati.py", line 160, in __init__
    self.enumerate_subdomains(domain, proxy)
  File "Belati.py", line 248, in enumerate_subdomains
    self.banner_grab(self.url_req.ssl_checker(subdomain), proxy)
  File "/private/var/root/Belati/plugins/url_request.py", line 140, in ssl_checker
    data = urllib2.urlopen("https://{}".format(domain), timeout=25, context=gcontext)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
**socket.error: [Errno 54] Connection reset by peer**

**Comment by aancw** [comment]
Hi,
I think this is SSL Problem. Your target available for SSL connection? 
```
File "/private/var/root/Belati/plugins/url_request.py", line 140, in ssl_checker
data = urllib2.urlopen("https://{}".format(domain), timeout=25, context=gcontext)
```

**Comment by aancw** [comment]
Can you edit `Belati/plugins/url_request.py`?
Change from 
`if not "ERROR" in data:`
to this
`if not "ERROR" in data or if not "Errno" in data:`

@birdpillow  Lemme know if this is work. Thanks!

**Comment by aancw** [comment]
Hi @birdpillow ,

I've fixing this bug, please update Belati with command `git pull` :)

Lemme know if this is work.

**Comment by birdpillow** [comment]
Git pull its oke.
But still not working
Traceback (most recent call last):
  File "Belati.py", line 430, in <module>
    BelatiApp = Belati()
  File "Belati.py", line 160, in __init__
    self.enumerate_subdomains(domain, proxy)
  File "Belati.py", line 248, in enumerate_subdomains
    self.banner_grab(self.url_req.ssl_checker(subdomain), proxy)
  File "/private/var/root/Belati/plugins/url_request.py", line 141, in ssl_checker
    data = urllib2.urlopen("https://{}".format(domain), timeout=25, context=gcontext)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1200, in do_open
    r = h.getresponse(buffering=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 734, in recv
    return self.read(buflen)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
**socket.error: [Errno 54] Connection reset by peer**

**Comment by aancw** [comment]
@birdpillow, can you PM me about your target? Maybe i can try in my environment and try to fix this issue. 

cacaddv@gmail.com

Thanks :)

**Comment by birdpillow** [comment]
I try to 1337x.to

Mints:Belati root# python Belati.py -d https://1337x.to

        

         /$$$$$$$  /$$$$$$$$ /$$        /$$$$$$  /$$$$$$$$     .
        | $$__  $$| $$_____/| $$       /$$__  $$|__  $$__/    J:L
        | $$  \ $$| $$      | $$      | $$  \ $$   | $$       |:|
        | $$$$$$$ | $$$$$   | $$      | $$$$$$$$   | $$       |:|
        | $$__  $$| $$__/   | $$      | $$__  $$   | $$       |:|
        | $$  \ $$| $$      | $$      | $$  | $$   | $$       |:|
        | $$$$$$$/| $$$$$$$$| $$$$$$$$| $$  | $$   | $$   /]  |:|  [\ 
        |_______/ |________/|________/|__/  |__/   |__/   \:-'"""'-:/
                                                            ""III""
                                                              III
                                                              III
                                                              III
                                                             (___)

                                The Traditional Swiss Army Knife for OSINT

        =[ Belati v0.2.3-dev by Petruknisme]=

        + -- --=[ Collecting Public Data & Public Document for OSINT purpose ]=-- -- +
        + -- --=[ https://petruknisme.com ]=-- -- +
        
        

        
        This tool is for educational purposes only.
        Any damage you make will not affect the author.
        Do It With Your Own Risk!

        For Better Privacy, Please Use proxychains or other proxy service!
        
        
[*] Starting at: 2017-12-04 16:55:47 
[+] Checking Network Connection... OK 
[+] Checking Version Update for Belati... 
[+] Belati version is uptodate \m/
[+] Creating New Belati Project... 
---------------------------------------------------------
Project ID: 2
Project Domain: https://1337x.to
Project Organization/Company: None
---------------------------------------------------------
[*] Checking Domain Availability... NOT OK!
[*] Checking URL Alive... NOT OK! 
[*] Perfoming Whois... 
Socket Error: timed out
{
  "updated_date": null, 
  "status": null, 
  "name": null, 
  "dnssec": null, 
  "city": null, 
  "expiration_date": null, 
  "zipcode": null, 
  "domain_name": null, 
  "country": null, 
  "whois_server": null, 
  "state": null, 
  "registrar": null, 
  "referral_url": null, 
  "address": null, 
  "name_servers": null, 
  "org": null, 
  "creation_date": null, 
  "emails": null
}
[*] Perfoming HTTP Banner Grabbing... 
ERROR <urlopen error [Errno 8] nodename nor servname provided, or not known>
1
[*] Perfoming Subdomains Enumeration... 
Error: Please enter a valid domain
[*] Perfoming DNS Zone Scanning... 
[*] Please wait, maximum timeout for checking is 1 minutes 
[*] No response from server... SKIP!
[*] Perfoming Email Harvest from Google Search...
[*] Found 0 emails on domain https://1337x.to

[*] Perfoming Email Harvest from PGP Server...
Error code: 404
[-] Not found or Unavailable. None
[*] Perfoming Public Document Harvest from Google... 
[*] Gather Link from Google Search for domain https://1337x.to
[*] Searching PDF Document... 
[*] Searching DOC Document... 
[*] Searching XLS Document... 
[*] Searching ODT Document... 
[*] Searching PPT Document... 
[*] Searching RTF Document... 
[*] Searching TXT Document... 
All done sir! All logs saved in `log` directory and dowloaded file saved in `belatiFiles` 
Starting Django Web Server at http://0.0.0.0:8000/
System check identified some issues:

WARNINGS:
?: (1_7.W001) MIDDLEWARE_CLASSES is not set.
	HINT: Django 1.7 changed the global defaults for the MIDDLEWARE_CLASSES. django.contrib.sessions.middleware.SessionMiddleware, django.contrib.auth.middleware.AuthenticationMiddleware, and django.contrib.messages.middleware.MessageMiddleware were removed from the defaults. If your project needs these middleware then you should configure this setting.

System check identified 1 issue (0 silenced).
No Response...

**Comment by aancw** [comment]
Can you try without `https://` ?

**Comment by aancw** [comment]
I wil close this issue. Please open again when you are stil happening this problem.
