### ISSUE TITLE
"No module named CheckMyUsername"

### ISSUE THREAD

**Issue by muhfaris** [aancw/Belati#3]
i want try this tool, but i get error like this :   

`Traceback (most recent call last):
  File "Belati.py", line 46, in <module>
    from lib.CheckMyUsername.check_my_username import CheckMyUsername
ImportError: No module named CheckMyUsername.check_my_username
`

and try to run unprivileges root like this :   

`→ python2.7 Belati.py --help
Traceback (most recent call last):
  File "Belati.py", line 23, in <module>
    from plugins.dep_check import DepCheck
  File "/opt/Belati/plugins/dep_check.py", line 33, in <module>
    log = Logger()
  File "/opt/Belati/plugins/logger.py", line 38, in __init__
    if exc.errno != errno.EEXIST:
NameError: global name 'errno' is not defined
`  
  
i hope you can fix this problem
Best regards

**Comment by aancw** [comment]
Please update submodule repo. I've already note about this in Install/Usage:

```
git submodule update --init --recursive
pip install -r requirements.txt #please use pip with python v2
```

I've forgot to put `errno` in import, but it will be fine if no error in logger. I will update this repo after core modules is finished.

And, please read README.md :)

**Comment by muhfaris** [comment]
I've been doing it, but not solved problem  
```
[root@arch Belati]# python2.7 Belati.py --help  
Traceback (most recent call last):  
  File "Belati.py", line 46, in <module>  
    from lib.CheckMyUsername.check_my_username import CheckMyUsername  
ImportError: No module named CheckMyUsername.check_my_username  

[root@arch Belati]# git submodule update --init --recursive  

[root@arch Belati]# pip2 install -r requirements.txt #please use pip with python v2  
Requirement already satisfied: dnspython in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: argparse in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: texttable in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: python-geoip-geolite2 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: python-geoip in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: dnsknife in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: termcolor in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: colorama in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: validators in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: tqdm in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: tldextract in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: fake-useragent in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 13))
Requirement already satisfied: python-wappalyzer in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 14))
Requirement already satisfied: future in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 15))
Requirement already satisfied: pycrypto in /usr/lib/python2.7/site-packages (from dnsknife->-r requirements.txt (line 7))
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from dnsknife->-r requirements.txt (line 7))
Requirement already satisfied: decorator>=3.4.0 in /usr/lib/python2.7/site-packages (from validators->-r requirements.txt (line 10))
Requirement already satisfied: setuptools in /usr/lib/python2.7/site-packages (from tldextract->-r requirements.txt (line 12))
Requirement already satisfied: idna in /usr/lib/python2.7/site-packages (from tldextract->-r requirements.txt (line 12))
Requirement already satisfied: requests-file>=1.4 in /usr/lib/python2.7/site-packages (from tldextract->-r requirements.txt (line 12))
Requirement already satisfied: BeautifulSoup==3.2.1 in /usr/lib/python2.7/site-packages (from python-wappalyzer->-r requirements.txt (line 14))
Requirement already satisfied: packaging>=16.8 in /usr/lib/python2.7/site-packages (from setuptools->tldextract->-r requirements.txt (line 12))
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python2.7/site-packages (from setuptools->tldextract->-r requirements.txt (line 12))
Requirement already satisfied: pyparsing in /usr/lib/python2.7/site-packages (from packaging>=16.8->setuptools->tldextract->-r requirements.txt (line 12))


[root@arch Belati]# python2.7 Belati.py --help
Traceback (most recent call last):
  File "Belati.py", line 46, in <module>
    from lib.CheckMyUsername.check_my_username import CheckMyUsername
ImportError: No module named CheckMyUsername.check_my_username

```

**Comment by aancw** [comment]
Oh i see, this is because no `__init__.py` in `lib/CheckMyUsername/` folder. I've updated submodule repo https://github.com/aancw/CheckMyUsername/commit/8317e1c97988b0781fcc367aa0a75aae113090ad

Please update submodule repo again with:

`git submodule update --init --recursive`

Thanks!

**Comment by muhfaris** [comment]
Solved, thanks
