### ISSUE TITLE
Fails when google ask for captcha

### ISSUE THREAD

**Issue by melizeche** [aancw/Belati#7]
```
[*] Perfoming Public Document Harvest from Google... 
[*] Gather Link from Google Search for domain example.com
[*] Searching PDF Document... 
Error code: 503
Traceback (most recent call last):
  File "Belati.py", line 425, in <module>
    BelatiApp = Belati()
  File "Belati.py", line 144, in __init__
    self.harvest_document(domain, proxy)
  File "Belati.py", line 313, in harvest_document
    public_doc.init_crawl(domain_name, proxy_address, self.project_id)
  File "/home/marce/tmp/Belati/plugins/harvest_public_document.py", line 49, in init_crawl
    self.harvest_public_doc(domain, "pdf", proxy_address)
  File "/home/marce/tmp/Belati/plugins/harvest_public_document.py", line 67, in harvest_public_doc
    data = re.findall(regex, data)
  File "/home/marce/tmp/Belati/env/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```

**Comment by aancw** [comment]
Yes, google sometime will blocking our request.
